shadowsocks:
  verbose: true
  key: change-this-to-something--secure
  client:
    enabled: false
  server:
    enabled: true
    v2ray:
      enabled: true
      host: "example.com"
      tls:
        enabled: false
      ingress:
        enabled: true
