apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-shadowsocks2.fullname" . }}
  labels:
    {{- include "go-shadowsocks2.labels" . | nindent 4 }}
stringData:
  keyfile: {{ required "Key is required" .Values.shadowsocks.key | b64enc | quote }}
