{{- with .Values.shadowsocks.client }}
{{- if and .enabled .socks.enabled }}
{{- with .socks }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-shadowsocks2.fullname" $ }}-socks
  labels:
    {{- include "go-shadowsocks2.labels" $ | nindent 4 }}
spec:
  type: {{ .serviceType }}
  ports:
    - name: socks
      targetPort: socks
    {{- if eq .serviceType "NodePort" }}
      nodePort: {{ required "socks node port is required" .nodePort }}
    {{- end }}
      port: {{ default 1080 .port }}
      protocol: TCP
  selector:
    {{- include "go-shadowsocks2.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
